### ISSUE TITLE
Crash in development environment

### ISSUE THREAD

**Issue by TCLProject** [makamys/Satchels#2]
Version of mod: 1.0.2
Version of forge: 1614
When crash happens: Immediately upon joining world
Crash report: 
[crash-2021-09-04_19.05.58-server.txt](https://github.com/makamys/Satchels/files/7110301/crash-2021-09-04_19.05.58-server.txt)
However it's pretty useless. More information is given in the console, namely:
http://hastebin.com/ukugapifuy.kotlin
Hoping you can take a look at this.

**Comment by makamys** [comment]
I'm guessing you're missing the program arguments for the mixin:
`--tweakClass org.spongepowered.asm.launch.MixinTweaker --mixin satchels.mixin.json`
Funnily enough, I was *just* thinking about adding this to the readme yesterday but forgot.

Added it now.

**Comment by TCLProject** [comment]
The crash still happens. In the log, I see "Completely ignored arguments: [--mixin, satchels.mixin.json]". Any idea as to why it's ignoring it?

**Comment by makamys** [comment]
You can ignore that message, it's not an error.

Does the crash happen with no other mods in the dev environment instance? Also, can you confirm `Reference map 'satchels.mixin.refmap.json' for satchels.mixin.json could not be read. If this is a development environment you can ignore this message` shows up in the log? That would confirm the mixin environment is running at least.

**Comment by New-Phoenix** [comment]
Sorry for the late reply. No, I cannot find `Reference map 'satchels.mixin.refmap.json` for satchels.mixin.json could not be read. If this is a development environment you can ignore this message` in the logs, but I can find `Remapping refMap satchels.mixin.refmap.json using..` etc. So I think mixin loads just fine. I deleted all other mods from development environment and it loads just fine, so I assume it was an incompatibility. Sadly can't say which mod though, I just deleted all 25+ of them without thinking ahead. I apologize again.

**Comment by TCLProject** [comment]
Sorry for the late reply. No, I cannot find `Reference map satchels.mixin.refmap.json for satchels.mixin.json could not be read. If this is a development environment you can ignore this message` in the logs, but I can find `Remapping refMap satchels.mixin.refmap.json using..` etc. So I think mixin loads just fine. I deleted all other mods from development environment and it loads without the crash, so I assume it was a mod incompatibility. Sadly can't say which mod though, I just deleted all 25+ of them without thinking ahead. I apologize again.

**Comment by makamys** [comment]
~~This is why you should always move files to the recycle bin first before permanently deleting them 😏~~
Just kidding, no worries. Glad it turned out to be just an incompatibility issue and not something more critical.
