### ISSUE TITLE
Satchel issues when coming back from the End dimension 

### ISSUE THREAD

**Issue by SilearFlare** [makamys/Satchels#5]
Making this because anon is a lazy shit and he won't open an issue himself
![Screenshot from 2022-04-10 21-06-20](https://user-images.githubusercontent.com/5557920/162635749-72ef4286-588a-4a8e-8ccc-56c3e391b8e5.png)
what a weenie

**Comment by makamys** [comment]
Fix'd.
I'll keep the flying items phenomenon because I think it's funny, and you're not supposed to take off your satchel/pouches while there's items in them anyway (it only happened here because anon was experiencing a bug).
